apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: py-gitops
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: py-gitops
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: py-gitops
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: ghcr.io/amagaeru/tap/source-codes:latest@sha256:0cabb37ad8f1f5ec4e164a8f3f88275a214d4e1f7380d9fe809ccac97f683179
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: py-gitops
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: py-gitops
    spec:
      containers:
      - image: ghcr.io/amagaeru/py-gitops-tap-openshift-w01-s005@sha256:71a1d808561e48fecf96379dfeb79201d9410a861bec861d9406f6ac35dce97e
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

