apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: py-gitops
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: py-gitops
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: py-gitops
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: ghcr.io/amagaeru/tap/source-codes:latest@sha256:88b0e91ca0836339b750ec44caf2299c6ae3ebfb448f7c79a65966b54c84e38e
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: py-gitops
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: py-gitops
    spec:
      containers:
      - image: ghcr.io/amagaeru/tkg211-hol04/workloads/py-gitops-tap-openshift-w01-s005@sha256:036d805b1d0422ea2a305e2199759ded4e04277ec9658e9c600f060e38702b18
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

